import { IntegrationMetadata } from './types';

export const INTEGRATION_REGISTRY: Record<string, IntegrationMetadata> = {
  DATABASE: {
    providerKey: 'DATABASE',
    name: 'Production Database (PostgreSQL / SQLite)',
    category: 'DATABASE',
    purpose: 'Core transactional datastore, user accounts, audit trails, and CRM pipeline.',
    environment: 'PRODUCTION',
    isRequired: true,
    isBootstrapOnly: true,
    docsHelp:
      'Database connection URL is a bootstrap/deployment-level secret. It must be provided in deployment environment variables (DATABASE_URL) before application startup because the server cannot boot without it.',
    fields: [
      {
        key: 'DATABASE_URL',
        label: 'Database Connection String',
        type: 'password',
        isSecret: true,
        required: true,
        placeholder: 'postgresql://postgres:password@db.region.supabase.co:5432/postgres',
        description: 'PostgreSQL or SQLite connection string provided at deployment.',
      },
    ],
  },

  SUPABASE: {
    providerKey: 'SUPABASE',
    name: 'Supabase Platform Integration',
    category: 'DATABASE',
    purpose: 'Managed PostgreSQL, authentication bridge, and real-time backend infrastructure.',
    environment: 'PRODUCTION',
    isRequired: false,
    isBootstrapOnly: false,
    docsHelp:
      'Locate your Project Settings -> API in your Supabase dashboard to find your Project URL, anon public key, and secret service_role key.',
    fields: [
      {
        key: 'projectUrl',
        label: 'Project URL',
        type: 'url',
        required: true,
        placeholder: 'https://xyzcompany.supabase.co',
        description: 'Supabase project endpoint URL.',
      },
      {
        key: 'anonKey',
        label: 'Anon / Public API Key',
        type: 'password',
        isSecret: true,
        required: true,
        placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        description: 'Public publishable client key.',
      },
      {
        key: 'serviceRoleKey',
        label: 'Service Role Key (Server-Side Only)',
        type: 'password',
        isSecret: true,
        required: false,
        placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        description: 'Server-side privileged key. Encrypted at rest; NEVER sent to client browsers.',
      },
    ],
  },

  UPSTOX: {
    providerKey: 'UPSTOX',
    name: 'Upstox API v2 (Market Data)',
    category: 'MARKET_DATA',
    purpose: 'Live tick feeds, NSE/BSE indices, market depth, and real-time OHLC quotes.',
    environment: 'PRODUCTION',
    isRequired: true,
    isBootstrapOnly: false,
    docsHelp:
      'Generate an API key in the Upstox Developer Console (https://developer.upstox.com). After creating an App, obtain your Client ID, Secret, and generate an interactive Access Token. Note: Upstox access tokens are session-based and expire daily at 03:30 AM IST.',
    fields: [
      {
        key: 'clientId',
        label: 'Client ID / API Key',
        type: 'text',
        required: true,
        placeholder: '2f0b98... (Upstox API Key)',
      },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        type: 'password',
        isSecret: true,
        required: true,
        placeholder: '••••••••••••',
      },
      {
        key: 'accessToken',
        label: 'Access Token (OAuth 2.0 Session Token)',
        type: 'password',
        isSecret: true,
        required: true,
        placeholder: 'Paste generated access token from daily login...',
        description: 'Daily session bearer token for Upstox API v2 requests.',
      },
      {
        key: 'baseUrl',
        label: 'API Base URL',
        type: 'url',
        required: false,
        placeholder: 'https://api.upstox.com/v2',
        description: 'Defaults to https://api.upstox.com/v2',
      },
      {
        key: 'redirectUri',
        label: 'Redirect URI',
        type: 'url',
        required: false,
        placeholder: 'https://yourdomain.com/api/integrations/upstox/callback',
      },
    ],
    defaultPublicConfig: {
      baseUrl: 'https://api.upstox.com/v2',
    },
  },

  SMC_GLOBAL: {
    providerKey: 'SMC_GLOBAL',
    name: 'SMC Global Securities (Authorised Person)',
    category: 'BROKER_GATEWAY',
    purpose: 'Brokerage gateway, Demat account onboarding referral link, and SMC Ace execution handoff.',
    environment: 'PRODUCTION',
    isRequired: true,
    isBootstrapOnly: false,
    docsHelp:
      'Tradosphere operates as an Authorised Person (AP) of SMC Global. Enter your registered AP Code, API Gateway credentials, and custom client onboarding portal URL.',
    fields: [
      {
        key: 'apCode',
        label: 'Authorised Person (AP) Code',
        type: 'text',
        required: true,
        placeholder: 'e.g. AP-SMC-998822',
        description: 'Unique AP identification code registered with SMC Global & NSE/BSE.',
      },
      {
        key: 'apiKey',
        label: 'SMC Partner API Key',
        type: 'password',
        isSecret: true,
        required: false,
        placeholder: '••••••••••••',
        description: 'Supplied once SMC grants direct partner technical integration access.',
      },
      {
        key: 'apiSecret',
        label: 'SMC Partner API Secret',
        type: 'password',
        isSecret: true,
        required: false,
        placeholder: '••••••••••••',
      },
      {
        key: 'onboardingUrl',
        label: 'Client Demat Onboarding URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.smcindiaonline.com',
        description: 'Official digital KYC & e-Sign onboarding portal for new clients.',
      },
      {
        key: 'tradingPortalUrl',
        label: 'SMC Ace Trading Portal URL',
        type: 'url',
        required: true,
        placeholder: 'https://smctradeonline.com',
        description: 'Official terminal where clients execute trades.',
      },
    ],
    defaultPublicConfig: {
      onboardingUrl: 'https://www.smcindiaonline.com',
      tradingPortalUrl: 'https://smctradeonline.com',
    },
  },

  AI_PROVIDER: {
    providerKey: 'AI_PROVIDER',
    name: 'AI Copilot Engine (Google Gemini / OpenAI)',
    category: 'AI',
    purpose: 'Powers Employee SOP lookup, CRM drafting assistance, and regulatory compliance checks.',
    environment: 'PRODUCTION',
    isRequired: true,
    isBootstrapOnly: false,
    docsHelp:
      'Provides LLM inference for the internal employee copilot. The AI Copilot operates strictly under TWM non-advisory compliance rules and will never provide stock tips or guaranteed returns.',
    fields: [
      {
        key: 'provider',
        label: 'Provider Name',
        type: 'select',
        required: true,
        options: [
          { label: 'Google Gemini (Recommended)', value: 'google' },
          { label: 'OpenAI', value: 'openai' },
          { label: 'Anthropic Claude', value: 'anthropic' },
          { label: 'Custom OpenAI-Compatible Endpoint', value: 'custom' },
        ],
      },
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        isSecret: true,
        required: true,
        placeholder: 'AIzaSy... or sk-...',
      },
      {
        key: 'model',
        label: 'Model Identifier',
        type: 'text',
        required: true,
        placeholder: 'gemini-1.5-flash or gpt-4o-mini',
      },
      {
        key: 'baseUrl',
        label: 'Base URL (Optional / Custom)',
        type: 'url',
        required: false,
        placeholder: 'https://api.openai.com/v1',
      },
    ],
    defaultPublicConfig: {
      provider: 'google',
      model: 'gemini-1.5-flash',
    },
  },

  EMAIL: {
    providerKey: 'EMAIL',
    name: 'Transactional Email Service',
    category: 'COMMUNICATION',
    purpose: 'Customer onboarding confirmation, application status updates, and administrative alerts.',
    environment: 'PRODUCTION',
    isRequired: false,
    isBootstrapOnly: false,
    docsHelp:
      'Configure an SMTP server or cloud email provider (Resend, SendGrid, Postmark, AWS SES). Test connection verifies server reachability without sending unsolicited emails.',
    fields: [
      {
        key: 'provider',
        label: 'Email Provider Type',
        type: 'select',
        required: true,
        options: [
          { label: 'SMTP Server', value: 'smtp' },
          { label: 'Resend API', value: 'resend' },
          { label: 'SendGrid API', value: 'sendgrid' },
          { label: 'Postmark API', value: 'postmark' },
        ],
      },
      {
        key: 'host',
        label: 'SMTP Host',
        type: 'text',
        required: false,
        placeholder: 'smtp.sendgrid.net or smtp.gmail.com',
      },
      {
        key: 'port',
        label: 'SMTP Port',
        type: 'number',
        required: false,
        placeholder: '587',
      },
      {
        key: 'username',
        label: 'SMTP Username',
        type: 'text',
        required: false,
        placeholder: 'apikey or admin@tradosphere.in',
      },
      {
        key: 'password',
        label: 'SMTP Password / API Key',
        type: 'password',
        isSecret: true,
        required: true,
        placeholder: '••••••••••••',
      },
      {
        key: 'senderEmail',
        label: 'From / Sender Email',
        type: 'text',
        required: true,
        placeholder: 'no-reply@tradosphere.in',
      },
      {
        key: 'senderName',
        label: 'From / Sender Name',
        type: 'text',
        required: false,
        placeholder: 'Tradosphere Wealth Management',
      },
    ],
    defaultPublicConfig: {
      provider: 'smtp',
      port: 587,
      senderName: 'Tradosphere Wealth Management',
      senderEmail: 'no-reply@tradosphere.in',
    },
  },

  STORAGE: {
    providerKey: 'STORAGE',
    name: 'Document Storage Vault',
    category: 'STORAGE',
    purpose: 'Secure encrypted storage for client KYC documents (PAN, Aadhaar, Cheques, Bank Statements).',
    environment: 'PRODUCTION',
    isRequired: true,
    isBootstrapOnly: false,
    docsHelp:
      'Choose Local Storage (filesystem with server-side role gating) or an S3-compatible cloud storage bucket (AWS S3, Cloudflare R2, Supabase Storage).',
    fields: [
      {
        key: 'driver',
        label: 'Storage Driver',
        type: 'select',
        required: true,
        options: [
          { label: 'Local Encrypted Filesystem', value: 'local' },
          { label: 'Amazon S3 / S3-Compatible', value: 's3' },
          { label: 'Cloudflare R2', value: 'r2' },
          { label: 'Supabase Storage', value: 'supabase' },
        ],
      },
      {
        key: 'bucket',
        label: 'Bucket / Container Name',
        type: 'text',
        required: false,
        placeholder: 'twm-kyc-documents-production',
      },
      {
        key: 'region',
        label: 'Bucket Region',
        type: 'text',
        required: false,
        placeholder: 'ap-south-1',
      },
      {
        key: 'endpoint',
        label: 'Custom S3 Endpoint (if applicable)',
        type: 'url',
        required: false,
        placeholder: 'https://<account-id>.r2.cloudflarestorage.com',
      },
      {
        key: 'accessKeyId',
        label: 'Access Key ID',
        type: 'text',
        required: false,
        placeholder: 'AKIA...',
      },
      {
        key: 'secretAccessKey',
        label: 'Secret Access Key',
        type: 'password',
        isSecret: true,
        required: false,
        placeholder: '••••••••••••',
      },
    ],
    defaultPublicConfig: {
      driver: 'local',
      bucket: 'twm-local-vault',
    },
  },

  NOTIFICATIONS: {
    providerKey: 'NOTIFICATIONS',
    name: 'Notifications Subsystem',
    category: 'COMMUNICATION',
    purpose: 'In-app notification center with optional Push / SMS delivery integration.',
    environment: 'PRODUCTION',
    isRequired: true,
    isBootstrapOnly: false,
    docsHelp:
      'In-app database notifications are always enabled. If external Push or SMS is unconfigured, the system operates in IN-APP ONLY mode without attempting fake deliveries.',
    fields: [
      {
        key: 'mode',
        label: 'Notification Delivery Mode',
        type: 'select',
        required: true,
        options: [
          { label: 'In-App Notifications Only (Default)', value: 'IN_APP_ONLY' },
          { label: 'In-App + Transactional Email', value: 'IN_APP_EMAIL' },
          { label: 'In-App + SMS Gateway', value: 'IN_APP_SMS' },
        ],
      },
      {
        key: 'smsApiKey',
        label: 'SMS Gateway API Key (Optional)',
        type: 'password',
        isSecret: true,
        required: false,
        placeholder: '••••••••••••',
      },
    ],
    defaultPublicConfig: {
      mode: 'IN_APP_ONLY',
    },
  },

  MARKET_DATA: {
    providerKey: 'MARKET_DATA',
    name: 'Market Data Primary Provider',
    category: 'MARKET_DATA',
    purpose: 'Configures the primary market data feed provider (Upstox Feed vs Official NSE Directory).',
    environment: 'PRODUCTION',
    isRequired: true,
    isBootstrapOnly: false,
    docsHelp:
      'Select active provider. When UPSTOX is selected, the application queries Upstox v2 API using configured Upstox credentials. When DIRECTORY_FALLBACK is selected, the application displays verified NSE reference listings with an honest "Data Unavailable" notice.',
    fields: [
      {
        key: 'primaryProvider',
        label: 'Primary Market Data Source',
        type: 'select',
        required: true,
        options: [
          { label: 'Upstox v2 Live Market Data Feed', value: 'UPSTOX' },
          { label: 'Verified NSE Reference Directory (Safe Fallback)', value: 'DIRECTORY_FALLBACK' },
        ],
      },
    ],
    defaultPublicConfig: {
      primaryProvider: 'UPSTOX',
    },
  },
};
